name: kasi_chat
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  flutter:
    sdk: flutter
 
  #state management
  bloc: ^9.0.1
  flutter_bloc: ^9.1.1
  get_it: ^9.2.1

  #router
  go_router: ^17.0.1

  #localization
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter

  #supabase
  supabase_flutter: ^2.12.4

  #utilities
  equatable: ^2.0.8
  logger: ^2.6.2
  flex_color_scheme: ^8.4.0
  image_picker:
  path_provider: ^2.0.14
  path:
  uuid: ^3.0.7
  mime: ^2.0.0


dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0

flutter:
  generate: true
  uses-material-design: true
